from bs4 import BeautifulSoup

def remove_spaces(input):
    for country, modified_country in countries_spaces_dict.items():
        input = input.replace(country, modified_country)
    return input

def process_line(line):
    for synonym, country in countries_dict.items():
        line = line.replace(synonym, country)
        line = remove_spaces(line)
    return line

countries_spaces_dict = {
    'Bosnia and Herzegovina': 'Bosnia_and_Herzegovina',
    'Czech Republic': 'Czech_Republic',
    'Dominican Republic': 'Dominican_Republic',
    'Hong Kong': 'Hong_Kong',
    'Ivory Coast': 'Ivory_Coast',
    'New Zealand': 'New_Zealand',
    'Northern Ireland': 'Northern_Ireland',
    'Puerto Rico': 'Puerto_Rico',
    'Republic of Ireland': 'Republic_of_Ireland',
    'Saudi Arabia': 'Saudi_Arabia',
    'South Africa': 'South_Africa',
    'South Korea': 'South_Korea',
    'Soviet Union': 'Soviet_Union',
    'Sri Lanka': 'Sri_Lanka',
    'United Kingdom': 'United_Kingdom',
    'United States of America': 'United_States_of_America'
}

countries_dict = {
    'Dane': 'Denmark',
    'Czechoslovak': 'Czechoslovakia',
    'Trinidadian': 'Trinidad and Tobago',
    'Burmese': 'Burma',
    'Indonesian': 'Indonesia',
    'Hong Konger': 'Hong Kong',
    'Irishwoman': 'Northern Ireland Republic of Ireland',
    'Honduran': 'Honduras',
    'Bangladeshi': 'Bangladesh',
    'Czechoslovakian': 'Czechoslovakia',
    'Tunisian': 'Tunisia',
    'Solomon Islander': 'Solomon Islands',
    'UAE': 'United Arab Emirates',
    'Guyanese': 'Guyana',
    'Australian': 'Australia',
    'UK': 'United Kingdom',
    'Czech': 'Czech Republic',
    'Turkish': 'Turkey',
    'Dutch': 'Netherlands',
    'Moldovan': 'Moldova',
    'Irish': 'Northern Ireland Republic of Ireland',
    'Cuban': 'Cuba',
    'Serb': 'Serbia',
    'Puerto Rican': 'Puerto Rico',
    'Dominican': 'Dominican Republic',
    'New Zealander': 'New Zealand',
    'Lithuanian': 'Lithuania',
    'Thai': 'Thailand',
    'Icelandic': 'Iceland',
    'Yugoslav': 'Yugoslavia',
    'British': 'United Kingdom',
    'Namibian': 'Namibia',
    'Briton': 'United Kingdom',
    'Monégasque': 'Monaco',
    'Zambian': 'Zambia',
    'Portuguese': 'Portugal',
    'Bosnian': 'Bosnia and Herzegovina',
    'Burundian': 'Burundi',
    'Danish': 'Denmark',
    'Filipino': 'Philippines',
    'Hungarian': 'Hungary',
    'Kazakh': 'Kazakhstan',
    'Malaysian': 'Malaysia',
    'Swedish': 'Sweden',
    "Côte d'Ivoire": 'Ivory Coast',
    'Sudanese': 'Sudan',
    'Croat': 'Croatia',
    'South African': 'South Africa',
    'Ghanaian': 'Ghana',
    'Icelander': 'Iceland',
    'Somali': 'Somalia',
    'Tswana': 'Botswana',
    'Cape Verdean': 'Cape Verde Islands',
    'Maltese': 'Malta',
    'Guatemalan': 'Guatemala',
    'Swiss': 'Switzerland',
    'Beninese': 'Benin',
    'Spanish': 'Spain',
    'Pole': 'Poland',
    'Chadian': 'Chad',
    'Gabonese': 'Gabon',
    'British': 'Britain',
    'Malian': 'Mali',
    'Liechtensteiner': 'Liechtenstein',
    'Venezuelan': 'Venezuela',
    'Slovene': 'Slovenia',
    'Scottish': 'Scotland',
    'Haitian': 'Haiti',
    'Jordanian': 'Jordan',
    'North Korean': 'North Korea',
    'Kenyan': 'Kenya',
    'Grenadian': 'Grenada',
    'Cameroonian': 'Cameroon',
    'Mauritian': 'Mauritius',
    'Russian': 'Russia',
    'Malagasy': 'Madagascar',
    'Zimbabwean': 'Zimbabwe',
    'Malawian': 'Malawi',
    'Lebanese': 'Lebanon',
    'Egyptian': 'Egypt',
    'Vanuatuan': 'Vanuatu',
    'Austrian': 'Austria',
    'Finnish': 'Finland',
    'Laotian': 'Laos',
    'Barbadian': 'Barbados',
    'Qatari': 'Qatar',
    'Saudi Arabian': 'Saudi Arabia',
    'Cypriot': 'Cyprus',
    'Chinese': 'China',
    'Western Samoan': 'Western Samoa',
    'Yemeni': 'Yemen',
    'Luxembourger': 'Luxembourg',
    'Frenchman': 'France',
    'Tobagonian': 'Trinidad and Tobago',
    'Tobagan': 'Trinidad and Tobago',
    'Swede': 'Sweden',
    'Georgian': 'Georgia',
    'Nigerien': 'Niger',
    'Nepalese': 'Nepal',
    'Belgian': 'Belgium',
    'US': 'United States of America',
    'American': 'United States of America',
    'Latvian': 'Latvia',
    'Peruvian': 'Peru',
    'Turkic': 'Turkey',
    'Turk': 'Turkey',
    'Hong Kongese': 'Hong Kong',
    'Englishman': 'England',
    'Iraqi': 'Iraq',
    'Bruneian': 'Brunei',
    'Afghan': 'Afghanistan',
    'Kuwaiti': 'Kuwait',
    'Canadian': 'Canada',
    'Serbian': 'Serbia',
    'Englishwoman': 'England',
    'Ukrainian': 'Ukraine',
    'Greek': 'Greece',
    'Zaïrean': 'Zaire',
    'Solomonian': 'Solomon Islands',
    'Welshman': 'Wales',
    'Tajik': 'Tajikistan',
    'Cambodian': 'Cambodia',
    'Turkmen': 'Turkmenistan',
    'Brazilian': 'Brazil',
    'Tadjik': 'Tajikistan',
    "Cote d'ivoire": 'Ivory Coast',
    'English': 'England',
    'Montenegrin': 'Montenegro',
    'Taiwanese': 'Taiwan',
    'Bhutanese': 'Bhutan',
    'Ivorian': 'Ivory Coast',
    'Botswanan': 'Botswana',
    'Bolivian': 'Bolivia',
    'Bahamian': 'Bahamas',
    'Macedonian': 'Macedonia',
    'Vietnamese': 'Vietnam',
    'Seychellois': 'Seychelles',
    'Ethiopian': 'Ethiopia',
    'Estonian': 'Estonia',
    'Senegalese': 'Senegal',
    'Spaniard': 'Spain',
    'Israeli': 'Israel',
    'Rwandan': 'Rwanda',
    'Liberian': 'Liberia',
    'Guinean': 'Papua New Guinea',
    'Singaporean': 'Singapore',
    'Tanzanian': 'Tanzania',
    'Japanese': 'Japan',
    'Emirates': 'United Arab Emirates',
    'Sierra Leonian': 'Sierra Leone',
    'Madagascan': 'Madagascar',
    'Polish': 'Poland',
    'Surinamer': 'Suriname',
    'Belarusian': 'Belarus',
    'Bahraini': 'Bahrain',
    'Algerian': 'Algeria',
    'USSR': 'Soviet Union',
    'Burkinese': 'Burkina',
    'Belarusan': 'Belarus',
    'Slovenian': 'Slovenia',
    'Chilean': 'Chile',
    'Costa Rican': 'Costa Rica',
    'Maldivian': 'Maldives',
    'Armenian': 'Armenia',
    'Ecuadorean': 'Ecuador',
    'Emirati': 'United Arab Emirates',
    'Mozambican': 'Mozambique',
    'Togolese': 'Togo',
    'Finn': 'Finland',
    'Turkoman': 'Turkmenistan',
    'Panamanian': 'Panama',
    'Angolan': 'Angola',
    'Scot': 'Scotland',
    'Syrian': 'Syria',
    'Frenchwoman': 'France',
    'Bulgarian': 'Bulgaria',
    'Croatian': 'Croatia',
    'Surinamese': 'Suriname',
    'Netherlander': 'Netherlands',
    'Paraguayan': 'Paraguay',
    'Nigerian': 'Nigeria',
    'German': 'Germany',
    'Tuvaluan': 'Tuvalu',
    'Uruguayan': 'Uruguay',
    'Mexican': 'Mexico',
    'Swazi': 'Swaziland',
    'Djiboutian': 'Djibouti',
    'Mauritanian': 'Mauritania',
    'Azerbaijani': 'Azerbaijan',
    'Libyan': 'Libya',
    'South Korean': 'South Korea',
    'Salvadorean': 'El Salvador',
    'French': 'France',
    'Nicaraguan': 'Nicaragua',
    'Omani': 'Oman',
    'Jamaican': 'Jamaica',
    'Uzbek': 'Uzbekistan',
    'Congolese': 'Congo',
    'Gambian': 'Gambia',
    'Dutchman': 'Netherlands',
    'Fijian': 'Fiji',
    'Ugandan': 'Uganda',
    'Argentinian': 'Argentina',
    'Papua New Guinean': 'Papua New Guinea',
    'Emirati': 'United Arab Emirates',
    'Indian': 'India',
    'Dutchwoman': 'Netherlands',
    'Eritrean': 'Eritrea',
    'Ivory Coaster': 'Ivory Coast',
    'Saudi': 'Saudi Arabia',
    'Iranian': 'Iran',
    'Philippine': 'Philippines',
    'Mongolian': 'Mongolia',
    'Pakistani': 'Pakistan',
    'Sri Lankan': 'Sri Lanka',
    'Welshwoman': 'Wales',
    'Albanian': 'Albania',
    'Romanian': 'Romania',
    'Welsh': 'Wales',
    'Italian': 'Italy',
    'Slovak': 'Slovakia',
    'Colombian': 'Colombia',
    'Surinamese': 'Suriname',
    'Irishman': 'Northern Ireland Republic of Ireland',
    'Belizean': 'Belize',
    'Monacan': 'Monaco',
    'Norwegian': 'Norway',
    'Andorran': 'Andorra',
    'Moroccan': 'Morocco'
}

# html_content = open('countries_table.html', mode='r', encoding='utf8')
# soup = BeautifulSoup(html_content, "html.parser")
# rows = soup.find_all("tr")
#
# for row in rows:
#     cells = row.find_all("td")
#     country = cells[0].text
#     for cell in cells:
#         descriptions = cell.text.split('&')
#         for desc in descriptions:
#             if desc and desc != country:
#                 countries_dict[desc] = country
#                 print(desc + ' -> ' + country)
# print(countries_dict)

