
def remove_spaces(input):
    for country, modified_country in countries_spaces_dict.items():
        input = input.replace(country, modified_country)
    return input

def process_line(line):
    for synonym, country in countries_dict.items():
        line = line.replace(synonym, country)
        line = remove_spaces(line)
    return line

countries_spaces_dict = {
    'bosnia and herzegovina': 'bosnia_and_herzegovina',
    'czech republic': 'czech_republic',
    'dominican republic': 'dominican_republic',
    'hong kong': 'hong_kong',
    'ivory coast': 'ivory_coast',
    'new zealand': 'new_zealand',
    'northern ireland': 'northern_ireland',
    'puerto rico': 'puerto_rico',
    'republic of ireland': 'republic_of_ireland',
    'saudi arabia': 'saudi_arabia',
    'south africa': 'south_africa',
    'south korea': 'south_korea',
    'soviet union': 'soviet_union',
    'sri lanka': 'sri_lanka',
    'united kingdom': 'united_kingdom',
    'united states of america': 'united_states_of_america'
}

countries_dict = {
    'dane': 'denmark',
    'czechoslovak': 'czechoslovakia',
    'trinidadian': 'trinidad and tobago',
    'burmese': 'burma',
    'indonesian': 'indonesia',
    'hong konger': 'hong kong',
    'irishwoman': 'northern ireland republic of ireland',
    'honduran': 'honduras',
    'bangladeshi': 'bangladesh',
    'czechoslovakian': 'czechoslovakia',
    'tunisian': 'tunisia',
    'solomon islander': 'solomon islands',
    'uae': 'united arab emirates',
    'guyanese': 'guyana',
    'australian': 'australia',
    'uk': 'united kingdom',
    'czech': 'czech republic',
    'turkish': 'turkey',
    'dutch': 'netherlands',
    'moldovan': 'moldova',
    'irish': 'northern ireland republic of ireland',
    'cuban': 'cuba',
    'serb': 'serbia',
    'puerto rican': 'puerto rico',
    'dominican': 'dominican republic',
    'new zealander': 'new zealand',
    'lithuanian': 'lithuania',
    'thai': 'thailand',
    'icelandic': 'iceland',
    'yugoslav': 'yugoslavia',
    'british': 'united kingdom',
    'namibian': 'namibia',
    'briton': 'united kingdom',
    'monégasque': 'monaco',
    'zambian': 'zambia',
    'portuguese': 'portugal',
    'bosnian': 'bosnia and herzegovina',
    'burundian': 'burundi',
    'danish': 'denmark',
    'filipino': 'philippines',
    'hungarian': 'hungary',
    'kazakh': 'kazakhstan',
    'malaysian': 'malaysia',
    'swedish': 'sweden',
    "côte d'ivoire": 'ivory coast',
    'sudanese': 'sudan',
    'croat': 'croatia',
    'south african': 'south africa',
    'ghanaian': 'ghana',
    'icelander': 'iceland',
    'somali': 'somalia',
    'tswana': 'botswana',
    'cape verdean': 'cape verde islands',
    'maltese': 'malta',
    'guatemalan': 'guatemala',
    'swiss': 'switzerland',
    'beninese': 'benin',
    'spanish': 'spain',
    'pole': 'poland',
    'chadian': 'chad',
    'gabonese': 'gabon',
    'british': 'britain',
    'malian': 'mali',
    'liechtensteiner': 'liechtenstein',
    'venezuelan': 'venezuela',
    'slovene': 'slovenia',
    'scottish': 'scotland',
    'haitian': 'haiti',
    'jordanian': 'jordan',
    'north korean': 'north korea',
    'kenyan': 'kenya',
    'grenadian': 'grenada',
    'cameroonian': 'cameroon',
    'mauritian': 'mauritius',
    'russian': 'russia',
    'malagasy': 'madagascar',
    'zimbabwean': 'zimbabwe',
    'malawian': 'malawi',
    'lebanese': 'lebanon',
    'egyptian': 'egypt',
    'vanuatuan': 'vanuatu',
    'austrian': 'austria',
    'finnish': 'finland',
    'laotian': 'laos',
    'barbadian': 'barbados',
    'qatari': 'qatar',
    'saudi arabian': 'saudi arabia',
    'cypriot': 'cyprus',
    'chinese': 'china',
    'western samoan': 'western samoa',
    'yemeni': 'yemen',
    'luxembourger': 'luxembourg',
    'frenchman': 'france',
    'tobagonian': 'trinidad and tobago',
    'tobagan': 'trinidad and tobago',
    'swede': 'sweden',
    'georgian': 'georgia',
    'nigerien': 'niger',
    'nepalese': 'nepal',
    'belgian': 'belgium',
    'us': 'united states of america',
    'american': 'united states of america',
    'latvian': 'latvia',
    'peruvian': 'peru',
    'turkic': 'turkey',
    'turk': 'turkey',
    'hong kongese': 'hong kong',
    'englishman': 'england',
    'iraqi': 'iraq',
    'bruneian': 'brunei',
    'afghan': 'afghanistan',
    'kuwaiti': 'kuwait',
    'canadian': 'canada',
    'serbian': 'serbia',
    'englishwoman': 'england',
    'ukrainian': 'ukraine',
    'greek': 'greece',
    'zaïrean': 'zaire',
    'solomonian': 'solomon islands',
    'welshman': 'wales',
    'tajik': 'tajikistan',
    'cambodian': 'cambodia',
    'turkmen': 'turkmenistan',
    'brazilian': 'brazil',
    'tadjik': 'tajikistan',
    "cote d'ivoire": 'ivory coast',
    'english': 'england',
    'montenegrin': 'montenegro',
    'taiwanese': 'taiwan',
    'bhutanese': 'bhutan',
    'ivorian': 'ivory coast',
    'botswanan': 'botswana',
    'bolivian': 'bolivia',
    'bahamian': 'bahamas',
    'macedonian': 'macedonia',
    'vietnamese': 'vietnam',
    'seychellois': 'seychelles',
    'ethiopian': 'ethiopia',
    'estonian': 'estonia',
    'senegalese': 'senegal',
    'spaniard': 'spain',
    'israeli': 'israel',
    'rwandan': 'rwanda',
    'liberian': 'liberia',
    'guinean': 'papua new guinea',
    'singaporean': 'singapore',
    'tanzanian': 'tanzania',
    'japanese': 'japan',
    'emirates': 'united arab emirates',
    'sierra leonian': 'sierra leone',
    'madagascan': 'madagascar',
    'polish': 'poland',
    'surinamer': 'suriname',
    'belarusian': 'belarus',
    'bahraini': 'bahrain',
    'algerian': 'algeria',
    'ussr': 'soviet union',
    'burkinese': 'burkina',
    'belarusan': 'belarus',
    'slovenian': 'slovenia',
    'chilean': 'chile',
    'costa rican': 'costa rica',
    'maldivian': 'maldives',
    'armenian': 'armenia',
    'ecuadorean': 'ecuador',
    'emirati': 'united arab emirates',
    'mozambican': 'mozambique',
    'togolese': 'togo',
    'finn': 'finland',
    'turkoman': 'turkmenistan',
    'panamanian': 'panama',
    'angolan': 'angola',
    'scot': 'scotland',
    'syrian': 'syria',
    'frenchwoman': 'france',
    'bulgarian': 'bulgaria',
    'croatian': 'croatia',
    'surinamese': 'suriname',
    'netherlander': 'netherlands',
    'paraguayan': 'paraguay',
    'nigerian': 'nigeria',
    'german': 'germany',
    'tuvaluan': 'tuvalu',
    'uruguayan': 'uruguay',
    'mexican': 'mexico',
    'swazi': 'swaziland',
    'djiboutian': 'djibouti',
    'mauritanian': 'mauritania',
    'azerbaijani': 'azerbaijan',
    'libyan': 'libya',
    'south korean': 'south korea',
    'salvadorean': 'el salvador',
    'french': 'france',
    'nicaraguan': 'nicaragua',
    'omani': 'oman',
    'jamaican': 'jamaica',
    'uzbek': 'uzbekistan',
    'congolese': 'congo',
    'gambian': 'gambia',
    'dutchman': 'netherlands',
    'fijian': 'fiji',
    'ugandan': 'uganda',
    'argentinian': 'argentina',
    'papua new guinean': 'papua new guinea',
    'emirati': 'united arab emirates',
    'indian': 'india',
    'dutchwoman': 'netherlands',
    'eritrean': 'eritrea',
    'ivory coaster': 'ivory coast',
    'saudi': 'saudi arabia',
    'iranian': 'iran',
    'philippine': 'philippines',
    'mongolian': 'mongolia',
    'pakistani': 'pakistan',
    'sri lankan': 'sri lanka',
    'welshwoman': 'wales',
    'albanian': 'albania',
    'romanian': 'romania',
    'welsh': 'wales',
    'italian': 'italy',
    'slovak': 'slovakia',
    'colombian': 'colombia',
    'surinamese': 'suriname',
    'irishman': 'northern ireland republic of ireland',
    'belizean': 'belize',
    'monacan': 'monaco',
    'norwegian': 'norway',
    'andorran': 'andorra',
    'moroccan': 'morocco'
}

capitals_dict = {
        'vanuatu': 'port vila',
    'palestine': 'ramallah and gaza',
    'france': 'paris',
    'norway': 'oslo',
    'seychelles': 'victoria',
    'turks and caicos islands': 'cockburn town',
    'south korea': 'seoul',
    'nepal': 'kathmandu',
    'uganda': 'kampala',
    'ethiopia': 'addis ababa',
    'belize': 'belmopan',
    'bermuda': 'hamilton',
    'greece': 'athens',
    'bahrain': 'manama',
    'british virgin islands': 'road town',
    'liberia': 'monrovia',
    'mali': 'bamako',
    'greenland': 'nuuk',
    'cuba': 'havana',
    'venezuela': 'caracas',
    'thailand': 'bangkok',
    'barbados': 'bridgetown',
    'new zealand': 'wellington',
    'nigeria': 'abuja',
    'vatican city': 'vatican city',
    'croatia': 'zagreb',
    'aruba': 'oranjestad',
    'colombia': 'bogota',
    'kuwait': 'kuwait city',
    'belgium': 'brussels',
    'monaco': 'monaco',
    'austria': 'vienna',
    'sint maarten': 'philipsburg',
    'east timor': 'dili',
    'nauru': 'yaren',
    'iceland': 'reykjavik',
    'transnistria': 'tiraspol',
    'poland': 'warsaw',
    'taiwan': 'taipei',
    'saint pierre and miquelon': 'saint-pierre',
    'yemen': "sana'a", 'portugal': 'lisbon',
    'vietnam': 'hanoi',
    'bahamas': 'nassau',
    'somalia': 'mogadishu',
    'palau': 'ngerulmud',
    'anguilla': 'the valley',
    'ivory coast': 'yamoussoukro',
    'jamaica': 'kingston',
    'brazil': 'brasilia',
    'french guiana': 'cayenne',
    'niger': 'niamey',
    'guatemala': 'guatemala city',
    'd.r congo': 'kinshasa',
    'guinea-bissau': 'bissau',
    'pakistan': 'islamabad',
    'saint martin': 'philipsburg',
    'bulgaria': 'sofia',
    'paraguay': 'asuncion',
    'puerto rico': 'san juan',
    'israel': 'jerusalem',
    'trinidad and tobago': 'port of spain',
    'ghana': 'accra',
    'dominican republic': 'santo domingo',
    'spain': 'madrid',
    'madagascar': 'antananarivo',
    'botswana': 'gaborone',
    'luxembourg': 'luxembourg',
    'kazakhstan': 'astana',
    'bolivia': 'sucre',
    'christmas island': 'flying fish cove',
    'suriname': 'paramaribo',
    'estonia': 'tallinn',
    'cape verde': 'praia',
    'slovenia': 'ljubljana',
    'bangladesh': 'dhaka',
    'guam': 'hagatna',
    'south sudan': 'juba',
    'malaysia': 'kuala lumpur',
    'tanzania': 'dodoma',
    'japan': 'tokyo',
    'brunei': 'bandar seri begawan',
    'syria': 'damascus',
    'tonga': 'nukualofa',
    'cameroon': 'yaounde',
    'montenegro': 'podgorica',
    'montserrat': 'brades, plymouth',
    'gabon': 'libreville',
    'swaziland': 'mata-utu',
    'hungary': 'budapest',
    'jersey': 'saint helier',
    'mozambique': 'maputo',
    'honduras': 'tegucigalpa',
    'chad': "n'djamena", 'lesotho': 'maseru',
    'philippines': 'manila',
    'fiji': 'suva',
    'nicaragua': 'managua',
    'saint kitts and nevis': 'basseterre',
    'papua new guinea': 'port moresby',
    'republic of the congo': 'brazzaville',
    'tuvalu': 'funafuti',
    'guyana': 'georgetown',
    'czech republic': 'prague',
    'kiribati': 'tarawa',
    'slovakia': 'bratislava',
    'maldives': 'male',
    'united states of america': 'washington d.c.',
    'zimbabwe': 'harare',
    'azerbaijan': 'baku',
    'canada': 'ottawa',
    'gibraltar': 'gibraltar',
    'senegal': 'dakar',
    'new caledonia': 'noumea',
    'el salvador': 'san salvador',
    'china': 'beijing',
    'qatar': 'doha',
    'saint lucia': 'castries',
    'libya': 'tripoli',
    'kenya': 'nairobi',
    'kyrgyzstan': 'bishkek',
    'cambodia': 'phnom penh',
    'guinea': 'conakry',
    'uruguay': 'montevideo',
    'american samoa': 'pago pago',
    'zambia': 'lusaka',
    'micronesia': 'palikir',
    'faroe islands': 'torshavn',
    'tajikistan': 'dushanbe',
    'egypt': 'cairo',
    'dominica': 'roseau',
    'malawi': 'lilongwe',
    'bosnia and herzegovina': 'sarajevo',
    'united states virgin islands': 'charlotte amalie',
    'angola': 'luanda',
    'comoros': 'moroni',
    'central african republic': 'bangui',
    'myanmar': 'naypyidaw',
    'switzerland': 'bern',
    'sri lanka': 'sri jayawardenapura-kotte',
    'australia': 'canberra',
    'norfolk island': 'kingston',
    'afghanistan': 'kabul',
    'tokelau': 'nukunonu',
    'north korea': 'pyongyang',
    'isle of man': 'douglas',
    'burkina faso': 'ouagadougou',
    'laos': 'vientiane',
    'saint vincent and the grenadines': 'kingstown',
    'iraq': 'baghdad',
    'wallis and futuna': 'mata-utu',
    'northern mariana islands': 'saipan',
    'western sahara': 'el aaiun',
    'mauritania': 'nouakchott',
    'malta': 'valletta',
    'marshall islands': 'majuro',
    'georgia': 'tbilisi',
    'hong kong': 'hong kong city',
    'algeria': 'algiers',
    'iran': 'tehran',
    'morocco': 'rabat',
    'armenia': 'yerevan',
    'bhutan': 'thimphu',
    'ukraine': 'kiev',
    'sweden': 'stockholm',
    'lithuania': 'vilnius',
    'equatorial guinea': 'malabo',
    'denmark': 'copenhagen',
    'saudi arabia': 'riyadh',
    'andorra': 'andorra la vella',
    'niue': 'alofi',
    'india': 'new delhi',
    'italy': 'rome',
    'costa rica': 'san jose',
    'chile': 'santiago',
    'united kingdom': 'london',
    'pitcairn islands': 'adamstown',
    'kosovo': 'pristina',
    'grenada': "st. george's", 'moldova': 'chisinau',
    'finland': 'helsinki',
    'djibouti': 'djibouti-city',
    'sudan': 'khartoum',
    'cyprus': 'nicosia',
    'belarus': 'minsk',
    'mexico': 'mexico city',
    'antigua and barbuda': 'saint johns',
    'albania': 'tirana',
    'haiti': 'port-au-prince',
    'russia': 'moscow',
    'benin': 'porto-novo',
    'cocos islands': 'west island',
    'togo': 'lome',
    'argentina': 'buenos aires',
    'falkland islands': 'stanley',
    'rwanda': 'kigali',
    'samoa': 'apia',
    'eritrea': 'asmara',
    'united arab emirates': 'abu dhabi',
    'oman': 'muscat',
    'turkey': 'ankara',
    'saint barthelemy': 'gustavia',
    'burundi': 'bujumbura',
    'french polynesia': 'papeete',
    'mauritius': 'port louis',
    'liechtenstein': 'vaduz',
    'south africa': 'cape town',
    'serbia': 'belgrade',
    'turkmenistan': 'ashgabat',
    'tunisia': 'tunis',
    'panama': 'panama city',
    'peru': 'lima',
    'namibia': 'windhoek',
    'romania': 'bucharest',
    'singapore': 'singapore',
    'curacao': 'willemstad',
    'solomon islands': 'honiara',
    'guernsey': 'saint peter port',
    'latvia': 'riga',
    'indonesia': 'jakarta',
    'saint helena, ascension, and tristan da cunha': 'jamestown',
    'sierra leone': 'freetown',
    'netherlands': 'amsterdam',
    'mongolia': 'ulan bator',
    'ecuador': 'quito',
    'cook islands': 'avarua',
    'lebanon': 'beirut',
    'ireland': 'dublin',
    'germany': 'berlin',
    'uzbekistan': 'tashkent',
    'sao tome and principe': 'sao tome',
    'jordan': 'amman',
    'gambia': 'banjul',
    'macedonia': 'skopje',
    'san marino': 'san marino',
    'cayman islands': 'george town'
}

# html_content = open('countries_table.html', mode='r', encoding='utf8')
# soup = beautifulsoup(html_content, "html.parser")
# rows = soup.find_all("tr")
#
# for row in rows:
#     cells = row.find_all("td")
#     country = cells[0].text
#     for cell in cells:
#         descriptions = cell.text.split('&')
#         for desc in descriptions:
#             if desc and desc != country:
#                 countries_dict[desc] = country
#                 print(desc + ' -> ' + country)
# print(countries_dict)

